########## Hauptmenü ##########

[[main]]
identifier = "approach"
name = "Ansatz"
title = "Ansatz"
url = "/de/approach/"
pageRef = "/approach"
weight = 10
[[main]]
identifier = "solutions"
name = "Lösungen"
title = "Lösungen"
url = "/de/solutions/"
pageRef = "/solutions"
weight = 20
	[[main]]
	identifier = "conversational-ai"
	parent = "solutions"
	name = "Conversational AI"
	title = "Conversational AI"
	url = "/de/solutions/smartcall-assistance/"
	pageRef = "/solutions/smartcall-assistance"
	weight = 22
	[[main]]
	identifier = "intelligent-document-processing"
	parent = "solutions"
	name = "Intelligente Dokumentenverarbeitung"
	title = "Intelligente Dokumentenverarbeitung"
	url = "/de/solutions/intelligent-document-processing/"
	pageRef = "/solutions/intelligent-document-processing"
	weight = 24
	[[main]]
	identifier = "ai-search-recommendation"
	parent = "solutions"
	name = "AI Search & Recommendation"
	title = "AI Search & Recommendation"
	url = "/de/solutions/ai-search-recommendation/"
	pageRef = "/solutions/ai-search-recommendation"
	weight = 26
[[main]]
identifier = "services"
name = "Dienstleistungen"
title = "Dienstleistungen"
url = "/de/services/"
pageRef = "/services"
weight = 30
[[main]]
identifier = "company"
name = "Unternehmen"
title = "Unternehmen"
url = "/de/company/"
pageRef = "/company"
weight = 40
	[[main]]
	identifier = "careers"
	parent = "company"
	name = "Karriere"
	title = "Karriere"
	url = "/de/company/careers/"
	pageRef = "/company/careers"
	weight = 42
	[[main]]
	identifier = "shared-knowledge"
	parent = "company"
	name = "Wissensdatenbank"
	title = "Wissensdatenbank"
	url = "/de/company/shared-knowledge/"
	pageRef = "/company/shared-knowledge"
	weight = 44
	[[main]]
	identifier = "faq"
	parent = "company"
	name = "Häufig gestellte Fragen"
	title = "Häufig gestellte Fragen"
	url = "/de/company/faq/"
	pageRef = "/company/faq"
	weight = 46
[[main]]
identifier = "contact"
name = "Kontakt"
title = "Kontakt"
url = "/de/contact/"
pageRef = "/contact"
weight = 50



########## Fußzeilenmenü ##########

[[footer]]
identifier = "home"
name = "Startseite"
url = "/de/"
pageRef = "/"
weight = 1

[[footer]]
identifier = "approach"
name = "Ansatz"
url = "/de/approach/"
pageRef = "/approach"
weight = 10
[[footer]]
identifier = "solutions"
name = "Lösungen"
url = "/de/solutions/"
pageRef = "/solutions"
weight = 20
	[[footer]]
	identifier = "conversational-ai"
	parent = "solutions"
	name = "Conversational AI"
	url = "/de/solutions/smartcall-assistance/"
	pageRef = "/solutions/smartcall-assistance"
	weight = 22
	[[footer]]
	identifier = "intelligent-document-processing"
	parent = "solutions"
	name = "Intelligente Dokumentenverarbeitung"
	url = "/de/solutions/intelligent-document-processing/"
	pageRef = "/solutions/intelligent-document-processing"
	weight = 24
	[[footer]]
	identifier = "ai-search-recommendation"
	parent = "solutions"
	name = "AI Search & Recommendation"
	url = "/de/solutions/ai-search-recommendation/"
	pageRef = "/solutions/ai-search-recommendation"
	weight = 26
[[footer]]
identifier = "services"
name = "Dienstleistungen"
url = "/de/dienstleistungen/"
pageRef = "/dienstleistungen"
weight = 30
[[footer]]
identifier = "company"
name = "Unternehmen"
url = "/de/services/"
pageRef = "/services"
weight = 40
	[[footer]]
	identifier = "careers"
	parent = "company"
	name = "Karriere"
	url = "/de/company/careers/"
	pageRef = "/company/careers"
	weight = 42
	[[footer]]
	identifier = "shared-knowledge"
	parent = "company"
	name = "Wissensdatenbank"
	url = "/de/company/shared-knowledge/"
	pageRef = "/company/shared-knowledge"
	weight = 44
	[[footer]]
	identifier = "faq"
	parent = "company"
	name = "Häufig gestellte Fragen"
	url = "/de/company/faq/"
	pageRef = "/company/faq"
	weight = 46
[[footer]]
identifier = "contact"
name = "Kontakt"
url = "/de/contact/"
pageRef = "/contact"
weight = 50
